### ISSUE TITLE
G03E missing

### ISSUE THREAD

**Issue by jonaspu** [epha/domain-datensatz#4]
- G03E ANDROGENS AND FEMALE SEX HORMONES IN COMBINATION

Is missing in the wirkstoffe.json file

**Comment by Jonas74** [comment]
A) G03E is missing.
B) The list below has no corresponding substance in Switzerland.

```text
A05AX,A07CA,A11AB,A11BA,A11DB,A11EA,A11EB,A11JB,A11JC,B05DA,B05DB,B05ZB,C01EX,D02AB,D02AC,D02AF,D02AX,D03AA,D05AA,D07XD,D11AA,D11AF,G02CA,J07AN,J07AX,L01CZ,M02AB,M02AC,N05CX,S02DC,V04CL,V04CX,V06DX,V07AB,V07AX,A02X,A07C,A11B,A11J,A13A,B05D,B05Z,R05X,V06D,V07A,A13,A15,V06,V07
```

@tajanawa Can you add G03E 
@curki Should we remove the others

**Comment by Jonas74** [comment]
@tajanawa  
- I guess we leave the codes in 1. (maybe except the ones ending on 50-55). What are your thoughts?
- In 2. the missing ones have to be provided. 

```
   ---
    1. Wirkstoffe provides codes not used in artikel (packungen)
    (except maybe Swissmedic)
    ---
      0 A01AC54
      1 A06AC55
      2 A06AD02
      3 A10BX04
      4 A10BX07
      5 A10BX09
      6 A10BX11
      7 A10BX12
      8 A12CE01
      9 A16AB81
     10 B02BD09
     11 B03AC01
     12 C01DA14
     13 C05AD04
     14 C05CA01
     15 C05CA51
     16 C09DA29
     17 G01AA11
     18 G03AC03
     19 G03CA09
     20 G03CA53
     21 H01BA06
     22 J05AX15
     23 J05AX16
     24 J05AX67
     25 L02AA02
     26 L04AC04
     27 N01BA01
     28 N02AA09
     29 N02AA59
     30 N04BC01
     31 N07XX09
     32 R03AK04
     33 R03AL01
     34 R03C
     35 R03CA
     36 R03CA02
     37 R03CC
     38 R03CC02
     39 V06
     40 V06D
     41 V06DX
    ---
    These codes in artikel (packungen) are not provided in wirkstoffe
    ---
      0 G03E
      1 H01BA01
      2 A16AX15
      3 N02CX08
```

**Comment by tajanawa** [comment]
1. Yes, for the moment I would leave all, doesn`t disturb and I don`t know
that maybe we need some day this dates

2. All found in Wirkstoffe?!
"H01BA01": "Argipressin",
"A16AX15": "Ethyltelotristat"
"N02CX08": "Galcanezumab"
"G03E": "Androgene und weibliche Sexualhormone in Kombination"


Am Fr., 7. Juni 2019 um 18:49 Uhr schrieb Marco <notifications@github.com>:

**Comment by jonaspu** [comment]
Just FIY: [WIDO ATC List](https://www.wido.de/publikationen-produkte/arzneimittel-klassifikation/amtliche-atc-klassifikation/)

Not sure how you get the codes now, but this one should have all of them.

**Comment by tajanawa** [comment]
you`re coming in the office today?

Am Di., 18. Juni 2019 um 09:17 Uhr schrieb jonaspu <notifications@github.com

**Comment by Jonas74** [comment]
@jonaspu Thx for the link, but we have to consider a few things.

The WIDO ATC List is a customised list from the [WHO](https://www.whocc.no/atc_ddd_index/). A few codes have been added to better specify combination products or add substances from newly registered products in Germany. So it is a branch from the standard.

We also customise the original list from the WHO and only include substances, which are available in Switzerland. Therefore the list should only be a more specific subset of the WHO. I think this approach avoids duplicates and ambiguities and makes testing easier.
